//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorShell.Expressions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorShell.Expressions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymus types are not serialized for safety reasons.
        /// </summary>
        internal static string AnonymusTypeNotSerialized {
            get {
                return ResourceManager.GetString("AnonymusTypeNotSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression can&apos;t be differentiated.
        /// </summary>
        internal static string CanotDifferentiate {
            get {
                return ResourceManager.GetString("CanotDifferentiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t know howto convert {0} to {1}.
        /// </summary>
        internal static string CantConvert {
            get {
                return ResourceManager.GetString("CantConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide by zero detected in function.
        /// </summary>
        internal static string DivideByZero {
            get {
                return ResourceManager.GetString("DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse an empty function.
        /// </summary>
        internal static string EmptyFunction {
            get {
                return ResourceManager.GetString("EmptyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exponent, got: {0}.
        /// </summary>
        internal static string ExpectedExponent {
            get {
                return ResourceManager.GetString("ExpectedExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after + or -.
        /// </summary>
        internal static string ExpectedExpression {
            get {
                return ResourceManager.GetString("ExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after ^ operator.
        /// </summary>
        internal static string ExpectedExpressionAfterExponent {
            get {
                return ResourceManager.GetString("ExpectedExpressionAfterExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after * or / operator.
        /// </summary>
        internal static string ExpectedExpressionAfterMultDiv {
            get {
                return ResourceManager.GetString("ExpectedExpressionAfterMultDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected mult or divide, got: {0}.
        /// </summary>
        internal static string ExpectedMultiplyDivide {
            get {
                return ResourceManager.GetString("ExpectedMultiplyDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected plus or minus, got: {0}.
        /// </summary>
        internal static string ExpectedPlussminus {
            get {
                return ResourceManager.GetString("ExpectedPlussminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression contains invalid token..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing {0} token.
        /// </summary>
        internal static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Logical expressions are supported for this operation.
        /// </summary>
        internal static string NotLogicExpression {
            get {
                return ResourceManager.GetString("NotLogicExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables not set on expression.
        /// </summary>
        internal static string NoVariables {
            get {
                return ResourceManager.GetString("NoVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complete operation on expression. Varaibles are not set.
        /// </summary>
        internal static string NoVariableValues {
            get {
                return ResourceManager.GetString("NoVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse given value as a number.
        /// </summary>
        internal static string NumberParseFailed {
            get {
                return ResourceManager.GetString("NumberParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed past the end of the function. Expected more tokens.
        /// </summary>
        internal static string OutOfTokens {
            get {
                return ResourceManager.GetString("OutOfTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization error occured.
        /// </summary>
        internal static string SerializationError {
            get {
                return ResourceManager.GetString("SerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some chars are left that can&apos;t be parsed.
        /// </summary>
        internal static string TrailingChars {
            get {
                return ResourceManager.GetString("TrailingChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token in Factor: {0}.
        /// </summary>
        internal static string UnexpectedTokenInFactior {
            get {
                return ResourceManager.GetString("UnexpectedTokenInFactior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function name: {0}.
        /// </summary>
        internal static string UnknownFuction {
            get {
                return ResourceManager.GetString("UnknownFuction", resourceCulture);
            }
        }
    }
}
