name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: .NET Publish
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="CalculatorShell-Release-$tag"
        dotnet publish -c Release -o "../$release_name" CalculatorShell/CalculatorShell.csproj
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "CalculatorShell-Release*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
